/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: PanzerFuchs (https://sketchfab.com/PanzerFuchs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kawaii-fila-shoe-da57ed64a8034c87a0729c4265d37df1
Title: Kawaii Fila Shoe
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model1(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.561, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert4SG} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.lambert4SG} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
